name: Release Publisher

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  publish_release:
    if: github.repository == 'fkd13/pingt'
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      - name: Build
        run: go build -o pingt -ldflags="-s -w" .
      - name: Compress Build
        run: sudo apt-get update && sudo apt-get install -y upx && upx --best --lzma pingt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "pingt"